export const siteMeta = {
  title: "Alexandroit",
  tagline: "Open-source JavaScript, Angular, React, and Vue libraries.",
  description:
    "Discover open-source JavaScript libraries, Angular components, React components, and Vue components from the Stackline portfolio, with live docs, GitHub repositories, npm packages, and release-family guides.",
  baseUrl: "https://alexandroit.github.io",
  heroTitle: "Open-source JavaScript, Angular, React, and Vue libraries with live docs.",
  heroSummary:
    "This site tracks the active documentation, release families, npm packages, and GitHub repositories behind the Stackline portfolio. Instead of a single marketing page, it works like a modern editorial archive with platform indexes, paginated project posts, and direct paths into every documentation site that is actually live today.",
  featuredIntro:
    "Featured releases focus on the packages with the clearest platform coverage, the deepest docs, and the biggest practical value for product teams shipping frontend software.",
  postsPerPage: 6,
  author: "Alexandro",
  publisher: "Alexandroit",
  locale: "en_US",
  themeColor: "#f4efe6",
  updatedAt: "2026-04-08",
  keywords: [
    "open source javascript libraries",
    "javascript ui libraries",
    "typescript libraries",
    "angular components",
    "react components",
    "vue components",
    "frontend libraries",
    "npm packages",
    "github repositories",
    "developer documentation",
  ],
  adSnippet: `<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6353624842390947"
     crossorigin="anonymous"></script>

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3KQ9KECXR9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3KQ9KECXR9');
</script>`,
};

export const platformMeta = {
  all: {
    label: "All projects",
    description:
      "The full Stackline archive, combining open-source JavaScript libraries and framework-specific Angular, React, and Vue components in one editorial index.",
  },
  vanilla: {
    label: "Vanilla JS",
    description:
      "Framework-agnostic JavaScript libraries, browser-first utilities, and TypeScript-ready packages that stand on their own and often power the wrapper libraries.",
  },
  angular: {
    label: "Angular",
    description:
      "Maintained Angular components and Angular libraries with live docs, framework-line compatibility, and product-oriented wrapper surfaces.",
  },
  react: {
    label: "React",
    description:
      "React components and React libraries with version-aware docs, published packages, and a strong focus on practical product integration.",
  },
  vue: {
    label: "Vue",
    description:
      "Vue components and Vue libraries with live demos, migration-friendly docs, and carefully scoped product surfaces.",
  },
};

export const navigationLinks = [
  { label: "Home", href: "/" },
  { label: "Archive", href: "/archive" },
  { label: "Vanilla JS", href: "/platform/vanilla" },
  { label: "Angular", href: "/platform/angular" },
  { label: "React", href: "/platform/react" },
  { label: "Vue", href: "/platform/vue" },
];

export const projects = [
  {
    slug: "client-errors",
    title: "Client Errors",
    platform: "vanilla",
    family: "Observability",
    version: "0.1.1",
    packageName: "@stackline/client-errors",
    docsUrl: "https://alexandroit.github.io/client-errors/",
    repoUrl: "https://github.com/alexandroit/client-errors",
    npmUrl: "https://www.npmjs.com/package/@stackline/client-errors",
    releaseStatus: "Public npm package",
    releaseLine: "Vanilla JS 0.1 line",
    featured: true,
    summary:
      "A lightweight browser error reporting SDK with normalized payloads, sanitization, source context, screenshots, and transport to any developer-defined endpoint.",
    highlights: ["Browser SDK", "Docs live", "Published on npm"],
  },
  {
    slug: "loading",
    title: "Loading",
    platform: "vanilla",
    family: "Loading states",
    version: "0.1.1",
    packageName: "@stackline/loading",
    docsUrl: "https://alexandroit.github.io/loading/",
    repoUrl: "https://github.com/alexandroit/loading",
    npmUrl: "https://www.npmjs.com/package/@stackline/loading",
    releaseStatus: "Public npm package",
    releaseLine: "Vanilla JS 0.1 line",
    featured: true,
    summary:
      "A framework-agnostic loading toolkit with spinners, overlays, skeletons, shimmer loaders, accessibility hooks, and anti-flicker behavior.",
    highlights: ["Foundation library", "Docs live", "Published on npm"],
  },
  {
    slug: "color",
    title: "Color",
    platform: "vanilla",
    family: "Design system",
    version: "0.1.1",
    packageName: "@stackline/color",
    docsUrl: "https://alexandroit.github.io/color/",
    repoUrl: "https://github.com/alexandroit/color",
    npmUrl: "https://www.npmjs.com/package/@stackline/color",
    releaseStatus: "Public npm package",
    releaseLine: "Vanilla JS 0.1 line",
    featured: true,
    summary:
      "A tiny framework-agnostic color picker foundation for modern web apps, with clean DOM controls and a compact browser-ready footprint.",
    highlights: ["Tiny footprint", "Docs live", "Published on npm"],
  },
  {
    slug: "resize-observer",
    title: "Resize Observer",
    platform: "vanilla",
    family: "Browser APIs",
    version: "4.0.5",
    packageName: "@stackline/resize-observer",
    docsUrl: "https://alexandroit.github.io/resize-observer/",
    repoUrl: "https://github.com/alexandroit/resize-observer",
    npmUrl: "https://www.npmjs.com/package/@stackline/resize-observer",
    releaseStatus: "Public npm package",
    releaseLine: "Vanilla JS 4.0 line",
    featured: false,
    summary:
      "A maintained ResizeObserver polyfill and ponyfill covering box size options from the latest spec, with focused docs for performance and browser behavior.",
    highlights: ["Polyfill", "Docs live", "Published on npm"],
  },
  {
    slug: "moment",
    title: "Moment",
    platform: "vanilla",
    family: "Date and time",
    version: "2.30.5",
    packageName: "@stackline/moment",
    docsUrl: "https://alexandroit.github.io/moment/",
    repoUrl: "https://github.com/alexandroit/moment",
    npmUrl: "https://www.npmjs.com/package/@stackline/moment",
    releaseStatus: "Public npm package",
    releaseLine: "Moment 2.30.x",
    featured: false,
    summary:
      "A maintained Moment.js fork with versioned docs, familiar API compatibility, and modern publishing hygiene for teams that still depend on the library.",
    highlights: ["Legacy-compatible", "Docs live", "Published on npm"],
  },
  {
    slug: "angular-loading",
    title: "Angular Loading",
    platform: "angular",
    family: "Loading states",
    version: "21.0.1",
    packageName: "@stackline/angular-loading",
    docsUrl: "https://alexandroit.github.io/angular-loading/",
    repoUrl: "https://github.com/alexandroit/angular-loading",
    npmUrl: "https://www.npmjs.com/package/@stackline/angular-loading",
    releaseStatus: "Public npm package",
    releaseLine: "Angular 21 family",
    featured: false,
    summary:
      "Angular wrapper components, directives, and service helpers for the Stackline loading foundation, documented across multiple Angular families.",
    highlights: ["Angular families", "Docs live", "Published on npm"],
  },
  {
    slug: "react-loading",
    title: "React Loading",
    platform: "react",
    family: "Loading states",
    version: "19.0.1",
    packageName: "@stackline/react-loading",
    docsUrl: "https://alexandroit.github.io/react-loading/",
    repoUrl: "https://github.com/alexandroit/react-loading",
    npmUrl: "https://www.npmjs.com/package/@stackline/react-loading",
    releaseStatus: "Public npm package",
    releaseLine: "React 19 family",
    featured: false,
    summary:
      "React wrapper components, overlays, and imperative helpers that carry the loading foundation into React release families with versioned docs.",
    highlights: ["React families", "Docs live", "Published on npm"],
  },
  {
    slug: "vue-loading",
    title: "Vue Loading",
    platform: "vue",
    family: "Loading states",
    version: "3.0.1",
    packageName: "@stackline/vue-loading",
    docsUrl: "https://alexandroit.github.io/vue-loading/",
    repoUrl: "https://github.com/alexandroit/vue-loading",
    npmUrl: "https://www.npmjs.com/package/@stackline/vue-loading",
    releaseStatus: "Public npm package",
    releaseLine: "Vue 3 family",
    featured: false,
    summary:
      "Vue components, directives, and composables for the Stackline loading system, with version-aware docs and framework-family coverage.",
    highlights: ["Vue families", "Docs live", "Published on npm"],
  },
  {
    slug: "angular-highcharts",
    title: "Angular Highcharts",
    platform: "angular",
    family: "Charts",
    version: "21.0.1",
    packageName: "@stackline/angular-highcharts",
    docsUrl: "https://alexandroit.github.io/angular-highcharts/",
    repoUrl: "https://github.com/alexandroit/angular-highcharts",
    npmUrl: "https://www.npmjs.com/package/@stackline/angular-highcharts",
    releaseStatus: "Public npm package",
    releaseLine: "Angular 21 family",
    featured: false,
    summary:
      "Angular wrapper components for Highcharts, Highstock, Highmaps, and related modules, with live docs and migration-aware release families.",
    highlights: ["Charts", "Docs live", "Published on npm"],
  },
  {
    slug: "react-highcharts",
    title: "React Highcharts",
    platform: "react",
    family: "Charts",
    version: "19.0.1",
    packageName: "@stackline/react-highcharts",
    docsUrl: "https://alexandroit.github.io/react-highcharts/",
    repoUrl: "https://github.com/alexandroit/react-highcharts",
    npmUrl: "https://www.npmjs.com/package/@stackline/react-highcharts",
    releaseStatus: "Public npm package",
    releaseLine: "React 19 family",
    featured: false,
    summary:
      "A thin React wrapper for Highcharts with versioned demos, familiar API shape, and a maintained docs surface for modern React release families.",
    highlights: ["Charts", "Docs live", "Published on npm"],
  },
  {
    slug: "vue-highcharts",
    title: "Vue Highcharts",
    platform: "vue",
    family: "Charts",
    version: "3.0.0",
    packageName: "@stackline/vue-highcharts",
    docsUrl: "https://alexandroit.github.io/vue-highcharts/",
    repoUrl: "https://github.com/alexandroit/vue-highcharts",
    npmUrl: "https://www.npmjs.com/package/@stackline/vue-highcharts",
    releaseStatus: "Public npm package",
    releaseLine: "Vue 3 family",
    featured: false,
    summary:
      "A thin Vue wrapper for Highcharts with versioned demos, framework-family docs, and a practical migration path for existing chart surfaces.",
    highlights: ["Charts", "Docs live", "Published on npm"],
  },
  {
    slug: "angular-data-table-component",
    title: "Angular Data Table Component",
    platform: "angular",
    family: "Tables",
    version: "21.0.0",
    packageName: "@stackline/angular-data-table-component",
    docsUrl: "https://alexandroit.github.io/angular-data-table-component/",
    repoUrl: "https://github.com/alexandroit/angular-data-table-component",
    npmUrl: "https://www.npmjs.com/package/@stackline/angular-data-table-component",
    releaseStatus: "Public npm package",
    releaseLine: "Angular 21 family",
    featured: false,
    summary:
      "A maintained Angular data table with sorting, selection, expansion, pagination, and versioned docs aligned to current Angular release families.",
    highlights: ["Data table", "Docs live", "Published on npm"],
  },
  {
    slug: "react-data-table-component",
    title: "React Data Table Component",
    platform: "react",
    family: "Tables",
    version: "9.1.1",
    packageName: "@stackline/react-data-table-component",
    docsUrl: "https://alexandroit.github.io/react-data-table-component/",
    repoUrl: "https://github.com/alexandroit/react-data-table-component",
    npmUrl: "https://www.npmjs.com/package/@stackline/react-data-table-component",
    releaseStatus: "Public npm package",
    releaseLine: "React 19 family",
    featured: false,
    summary:
      "A maintained React data table component with sorting, selection, expansion, theming, and versioned docs focused on production product teams.",
    highlights: ["Data table", "Docs live", "Published on npm"],
  },
  {
    slug: "angular-multiselect-dropdown",
    title: "Angular Multiselect Dropdown",
    platform: "angular",
    family: "Forms",
    version: "21.0.1",
    packageName: "@stackline/angular-multiselect-dropdown",
    docsUrl: "https://alexandroit.github.io/angular-multiselect-dropdown/",
    repoUrl: "https://github.com/alexandroit/angular-multiselect-dropdown",
    npmUrl: null,
    releaseStatus: "Docs live, package line maintained locally",
    releaseLine: "Angular 21 family",
    featured: false,
    summary:
      "A maintained Angular multiselect dropdown with long release-family history, versioned docs, and a focus on compatibility from legacy lines through Angular 21.",
    highlights: ["Form controls", "Docs live", "Version families"],
  },
  {
    slug: "react-multiselect-dropdown",
    title: "React Multiselect Dropdown",
    platform: "react",
    family: "Forms",
    version: "19.0.0",
    packageName: "@stackline/react-multiselect-dropdown",
    docsUrl: "https://alexandroit.github.io/react-multiselect-dropdown/",
    repoUrl: "https://github.com/alexandroit/react-multiselect-dropdown",
    npmUrl: "https://www.npmjs.com/package/@stackline/react-multiselect-dropdown",
    releaseStatus: "Public npm package",
    releaseLine: "React 19 family",
    featured: false,
    summary:
      "A maintained React multiselect dropdown with versioned demos and a settings model designed to stay familiar across framework families.",
    highlights: ["Form controls", "Docs live", "Published on npm"],
  },
  {
    slug: "ng-multiselect-dropdown",
    title: "NG Multiselect Dropdown",
    platform: "angular",
    family: "Forms",
    version: "6.0.3",
    packageName: "@stackline/ng-multiselect-dropdown",
    docsUrl: "https://alexandroit.github.io/ng-multiselect-dropdown/",
    repoUrl: "https://github.com/alexandroit/ng-multiselect-dropdown",
    npmUrl: null,
    releaseStatus: "Docs live, package line maintained locally",
    releaseLine: "Angular 16 to 21 families",
    featured: false,
    summary:
      "A maintained NG multiselect dropdown for recent Angular families, with template-driven forms, reactive forms, built-in search, and versioned docs.",
    highlights: ["Form controls", "Docs live", "Version families"],
  },
  {
    slug: "angular2-multiselect-dropdown",
    title: "Angular2 Multiselect Dropdown",
    platform: "angular",
    family: "Forms",
    version: "14.0.1",
    packageName: "@stackline/angular2-multiselect-dropdown",
    docsUrl: "https://alexandroit.github.io/angular2-multiselect-dropdown/",
    repoUrl: "https://github.com/alexandroit/angular2-multiselect-dropdown",
    npmUrl: null,
    releaseStatus: "Docs live, package line maintained locally",
    releaseLine: "Angular 14 to 21 compatibility line",
    featured: false,
    summary:
      "A legacy Angular multiselect family kept alive as a separate compatibility surface, with dedicated docs for the maintained release lines.",
    highlights: ["Legacy line", "Docs live", "Version families"],
  },
  {
    slug: "vue-google-maps",
    title: "Vue Google Maps",
    platform: "vue",
    family: "Maps",
    version: "3.0.0",
    packageName: "@stackline/vue-google-maps",
    docsUrl: "https://alexandroit.github.io/vue-google-maps/",
    repoUrl: "https://github.com/alexandroit/vue-google-maps",
    npmUrl: "https://www.npmjs.com/package/@stackline/vue-google-maps",
    releaseStatus: "Public npm package",
    releaseLine: "Vue 3 family",
    featured: false,
    summary:
      "A maintained Vue wrapper for the Google Maps JavaScript API with advanced markers, clustering, migration-friendly components, and live docs.",
    highlights: ["Maps", "Docs live", "Published on npm"],
  },
];
